###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.6
      container_name: mylius-spuren-de-mysql
      working_dir: /application
      volumes:
        - ./app/mylius-spuren:/application
      environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=mylius
        - MYSQL_USER=user
        - MYSQL_PASSWORD=secret
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: mylius-spuren-de-webserver
      working_dir: /application
      volumes:
          - ./app/mylius-spuren:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: docker/php-fpm
      container_name: mylius-spuren-de-php-fpm
      working_dir: /application
      volumes:
        - ./app/mylius-spuren:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

